---
name: Dispatch Build 

on: 
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Set the platforms to build [ linux/amd64, linux/arm64, linux/arm/v7 or linux/arm/v6]'
        required: false
        default: 'linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6'

jobs:
  dispatch-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dockerfiles and Context
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - id: docker_metadata
        uses: docker/metadata-action@v4.1.1
        with:
          labels: |
            maintainer=victor-rds
            org.opencontainers.image.authors='Victor R. Santos <victor-rds@users.noreply.github.com>'
          images: |
            victorrds/cgi-duc
          flavor: |
            latest=true
          tags: |
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.3.0

      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Build and Push
        id: docker_build_push
        uses: docker/build-push-action@v3.2.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: ${{ github.event.inputs.platforms }}
          context: .
          file: ./Dockerfile
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
          push: true